/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	apim_v1alpha1 "github.com/cdiscount/kong-operator/pkg/apis/apim/v1alpha1"
	versioned "github.com/cdiscount/kong-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/cdiscount/kong-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/cdiscount/kong-operator/pkg/client/listers/apim/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// KongRouteInformer provides access to a shared informer and lister for
// KongRoutes.
type KongRouteInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.KongRouteLister
}

type kongRouteInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewKongRouteInformer constructs a new informer for KongRoute type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewKongRouteInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredKongRouteInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredKongRouteInformer constructs a new informer for KongRoute type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredKongRouteInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApimV1alpha1().KongRoutes(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApimV1alpha1().KongRoutes(namespace).Watch(options)
			},
		},
		&apim_v1alpha1.KongRoute{},
		resyncPeriod,
		indexers,
	)
}

func (f *kongRouteInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredKongRouteInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *kongRouteInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apim_v1alpha1.KongRoute{}, f.defaultInformer)
}

func (f *kongRouteInformer) Lister() v1alpha1.KongRouteLister {
	return v1alpha1.NewKongRouteLister(f.Informer().GetIndexer())
}
