---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kongroute.k8s.cdiscount.com
spec:
  group: k8s.cdiscount.com
  names:
    kind: KongRoute
    listKind: KongRouteList
    plural: kongroutes
    singular: kongroute
    shortNames:
    - kgr
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kongservice.k8s.cdiscount.com
spec:
  group: k8s.cdiscount.com
  names:
    kind: KongService
    listKind: KongServiceList
    plural: kongservices
    singular: kongservice
    shortNames:
    - kgs
  scope: Namespaced
  version: v1
---
