---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kongroutes.apim.cdiscount.com
spec:
  group: apim.cdiscount.com
  names:
    kind: KongRoute
    listKind: KongRouteList
    plural: kongroutes
    singular: kongroute
    shortNames:
    - kgr
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kongservices.apim.cdiscount.com
spec:
  group: apim.cdiscount.com
  names:
    kind: KongService
    listKind: KongServiceList
    plural: kongservices
    singular: kongservice
    shortNames:
    - kgs
  scope: Namespaced
  version: v1alpha1
---
