/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/cdiscount/kong-operator/pkg/apis/apim/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKongRoutes implements KongRouteInterface
type FakeKongRoutes struct {
	Fake *FakeApimV1alpha1
	ns   string
}

var kongroutesResource = schema.GroupVersionResource{Group: "apim.cdiscount.com", Version: "v1alpha1", Resource: "kongroutes"}

var kongroutesKind = schema.GroupVersionKind{Group: "apim.cdiscount.com", Version: "v1alpha1", Kind: "KongRoute"}

// Get takes name of the kongRoute, and returns the corresponding kongRoute object, and an error if there is any.
func (c *FakeKongRoutes) Get(name string, options v1.GetOptions) (result *v1alpha1.KongRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(kongroutesResource, c.ns, name), &v1alpha1.KongRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KongRoute), err
}

// List takes label and field selectors, and returns the list of KongRoutes that match those selectors.
func (c *FakeKongRoutes) List(opts v1.ListOptions) (result *v1alpha1.KongRouteList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(kongroutesResource, kongroutesKind, c.ns, opts), &v1alpha1.KongRouteList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KongRouteList{ListMeta: obj.(*v1alpha1.KongRouteList).ListMeta}
	for _, item := range obj.(*v1alpha1.KongRouteList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kongRoutes.
func (c *FakeKongRoutes) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(kongroutesResource, c.ns, opts))

}

// Create takes the representation of a kongRoute and creates it.  Returns the server's representation of the kongRoute, and an error, if there is any.
func (c *FakeKongRoutes) Create(kongRoute *v1alpha1.KongRoute) (result *v1alpha1.KongRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(kongroutesResource, c.ns, kongRoute), &v1alpha1.KongRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KongRoute), err
}

// Update takes the representation of a kongRoute and updates it. Returns the server's representation of the kongRoute, and an error, if there is any.
func (c *FakeKongRoutes) Update(kongRoute *v1alpha1.KongRoute) (result *v1alpha1.KongRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(kongroutesResource, c.ns, kongRoute), &v1alpha1.KongRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KongRoute), err
}

// Delete takes name of the kongRoute and deletes it. Returns an error if one occurs.
func (c *FakeKongRoutes) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(kongroutesResource, c.ns, name), &v1alpha1.KongRoute{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKongRoutes) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(kongroutesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.KongRouteList{})
	return err
}

// Patch applies the patch and returns the patched kongRoute.
func (c *FakeKongRoutes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.KongRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(kongroutesResource, c.ns, name, data, subresources...), &v1alpha1.KongRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KongRoute), err
}
