/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/cdiscount/kong-operator/pkg/apis/apim/v1alpha1"
	scheme "github.com/cdiscount/kong-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KongServicesGetter has a method to return a KongServiceInterface.
// A group's client should implement this interface.
type KongServicesGetter interface {
	KongServices(namespace string) KongServiceInterface
}

// KongServiceInterface has methods to work with KongService resources.
type KongServiceInterface interface {
	Create(*v1alpha1.KongService) (*v1alpha1.KongService, error)
	Update(*v1alpha1.KongService) (*v1alpha1.KongService, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.KongService, error)
	List(opts v1.ListOptions) (*v1alpha1.KongServiceList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.KongService, err error)
	KongServiceExpansion
}

// kongServices implements KongServiceInterface
type kongServices struct {
	client rest.Interface
	ns     string
}

// newKongServices returns a KongServices
func newKongServices(c *ApimV1alpha1Client, namespace string) *kongServices {
	return &kongServices{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the kongService, and returns the corresponding kongService object, and an error if there is any.
func (c *kongServices) Get(name string, options v1.GetOptions) (result *v1alpha1.KongService, err error) {
	result = &v1alpha1.KongService{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kongservices").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KongServices that match those selectors.
func (c *kongServices) List(opts v1.ListOptions) (result *v1alpha1.KongServiceList, err error) {
	result = &v1alpha1.KongServiceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kongservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kongServices.
func (c *kongServices) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("kongservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a kongService and creates it.  Returns the server's representation of the kongService, and an error, if there is any.
func (c *kongServices) Create(kongService *v1alpha1.KongService) (result *v1alpha1.KongService, err error) {
	result = &v1alpha1.KongService{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("kongservices").
		Body(kongService).
		Do().
		Into(result)
	return
}

// Update takes the representation of a kongService and updates it. Returns the server's representation of the kongService, and an error, if there is any.
func (c *kongServices) Update(kongService *v1alpha1.KongService) (result *v1alpha1.KongService, err error) {
	result = &v1alpha1.KongService{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kongservices").
		Name(kongService.Name).
		Body(kongService).
		Do().
		Into(result)
	return
}

// Delete takes name of the kongService and deletes it. Returns an error if one occurs.
func (c *kongServices) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kongservices").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kongServices) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kongservices").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched kongService.
func (c *kongServices) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.KongService, err error) {
	result = &v1alpha1.KongService{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("kongservices").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
