/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/cdiscount/kong-operator/pkg/apis/apim/v1alpha1"
	scheme "github.com/cdiscount/kong-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KongRoutesGetter has a method to return a KongRouteInterface.
// A group's client should implement this interface.
type KongRoutesGetter interface {
	KongRoutes(namespace string) KongRouteInterface
}

// KongRouteInterface has methods to work with KongRoute resources.
type KongRouteInterface interface {
	Create(*v1alpha1.KongRoute) (*v1alpha1.KongRoute, error)
	Update(*v1alpha1.KongRoute) (*v1alpha1.KongRoute, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.KongRoute, error)
	List(opts v1.ListOptions) (*v1alpha1.KongRouteList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.KongRoute, err error)
	KongRouteExpansion
}

// kongRoutes implements KongRouteInterface
type kongRoutes struct {
	client rest.Interface
	ns     string
}

// newKongRoutes returns a KongRoutes
func newKongRoutes(c *ApimV1alpha1Client, namespace string) *kongRoutes {
	return &kongRoutes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the kongRoute, and returns the corresponding kongRoute object, and an error if there is any.
func (c *kongRoutes) Get(name string, options v1.GetOptions) (result *v1alpha1.KongRoute, err error) {
	result = &v1alpha1.KongRoute{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kongroutes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KongRoutes that match those selectors.
func (c *kongRoutes) List(opts v1.ListOptions) (result *v1alpha1.KongRouteList, err error) {
	result = &v1alpha1.KongRouteList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kongroutes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kongRoutes.
func (c *kongRoutes) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("kongroutes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a kongRoute and creates it.  Returns the server's representation of the kongRoute, and an error, if there is any.
func (c *kongRoutes) Create(kongRoute *v1alpha1.KongRoute) (result *v1alpha1.KongRoute, err error) {
	result = &v1alpha1.KongRoute{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("kongroutes").
		Body(kongRoute).
		Do().
		Into(result)
	return
}

// Update takes the representation of a kongRoute and updates it. Returns the server's representation of the kongRoute, and an error, if there is any.
func (c *kongRoutes) Update(kongRoute *v1alpha1.KongRoute) (result *v1alpha1.KongRoute, err error) {
	result = &v1alpha1.KongRoute{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kongroutes").
		Name(kongRoute.Name).
		Body(kongRoute).
		Do().
		Into(result)
	return
}

// Delete takes name of the kongRoute and deletes it. Returns an error if one occurs.
func (c *kongRoutes) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kongroutes").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kongRoutes) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kongroutes").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched kongRoute.
func (c *kongRoutes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.KongRoute, err error) {
	result = &v1alpha1.KongRoute{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("kongroutes").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
